import {IApexFareRow, IColumnDef} from "../interfaces/chart";

export const faresColumns: IColumnDef[] = [
  { name: 'Month', prop: 'Date', width: 50, type: '', colour: '' },
  { name: 'Airline', prop: 'Carrier', width: 50, type: '', colour: '' },
  // { name: 'Origin', prop: 'OriginAirport', width: 50, type: '', colour: '' },
  // { name: 'Destination Airport', prop: 'DestinationAirport', width: 50, type: '', colour: '' },
  { name: 'Six month', prop: 'SixMonthsFare', width: 50, type: '', colour: '' },
  { name: 'Three month', prop: 'ThreeMonthsFare', width: 50, type: '', colour: '' },
  { name: 'One month', prop: 'OneMonthFare', width: 50, type: '', colour: '' },
  { name: 'One week', prop: 'OneWeekFare', width: 50, type: '', colour: '' },
  { name: 'Average', prop: 'WeightedAverage', width: 50, type: '', colour: '' },
];

// TRAVEL MONTH	AIRLINE	ORIGIN	DESTINATION	CABIN	SECTOR LENGTH (MI)	6 MONTH	3 MONTH	1 MONTH	1 WEEK	WEIGHTED AVERAGE FARE


export const fares: IApexFareRow[] = [
    {
      "Date": "2021-12-01T00:00:00",
      "Carrier": "Air France",
      "CarrierId": 255,
      "CarrierCode": null,
      "OriginAirport": "Manchester International ",
      "OriginAirportId": 1975,
      "OriginAirportCode": null,
      "OriginCity": null,
      "OriginCityId": 0,
      "OriginCityCode": null,
      "OriginCountry": null,
      "OriginCountryId": 0,
      "OriginCountryCode": null,
      "OriginContinent": null,
      "OriginContinentId": 0,
      "OriginContinentCode": null,
      "DestinationAirport": "Europe",
      "DestinationAirportId": 0,
      "DestinationAirportCode": null,
      "DestinationCity": null,
      "DestinationCityId": 0,
      "DestinationCityCode": null,
      "DestinationCountry": null,
      "DestinationCountryId": 0,
      "DestinationCountryCode": null,
      "DestinationContinent": null,
      "DestinationContinentId": 0,
      "DestinationContinentCode": null,
      "SectorLength": 618.45,
      "Frequency": 0,
      "SixMonthsFare": 72.2218812508113,
      "ThreeMonthsFare": 73.24105830642105,
      "OneMonthFare": 90.48845217008486,
      "OneWeekFare": 98.47183676315645,
      "ForecastFare": null,
      "SixMonthDyf": null,
      "ThreeMonthDyf": null,
      "OneMonthDyf": null,
      "PublishedAirlineResult": null,
      "TotalCount": null,
      "WeightedAverage": 92.75540508025425,
      "FarePerDistanceUnit": 0.14998044317285836,
      "SectorLengthNM": 333.93628481535,
      "GovernmentTaxes": 0,
      "WeightedAverageGovernmentTaxes": 0,
      "CabinTypeId": 1,
      "CabinTypeName": "Economy"
    },
    {
      "Date": "2021-12-01T00:00:00",
      "Carrier": "Finnair",
      "CarrierId": 278,
      "CarrierCode": null,
      "OriginAirport": "Manchester International ",
      "OriginAirportId": 1975,
      "OriginAirportCode": null,
      "OriginCity": null,
      "OriginCityId": 0,
      "OriginCityCode": null,
      "OriginCountry": null,
      "OriginCountryId": 0,
      "OriginCountryCode": null,
      "OriginContinent": null,
      "OriginContinentId": 0,
      "OriginContinentCode": null,
      "DestinationAirport": "Europe",
      "DestinationAirportId": 0,
      "DestinationAirportCode": null,
      "DestinationCity": null,
      "DestinationCityId": 0,
      "DestinationCityCode": null,
      "DestinationCountry": null,
      "DestinationCountryId": 0,
      "DestinationCountryCode": null,
      "DestinationContinent": null,
      "DestinationContinentId": 0,
      "DestinationContinentCode": null,
      "SectorLength": 1907.99,
      "Frequency": 0,
      "SixMonthsFare": 254.54196996093,
      "ThreeMonthsFare": 238.8008715237765,
      "OneMonthFare": 163.839582627853,
      "OneWeekFare": 186.8267912675315,
      "ForecastFare": null,
      "SixMonthDyf": null,
      "ThreeMonthDyf": null,
      "OneMonthDyf": null,
      "PublishedAirlineResult": null,
      "TotalCount": null,
      "WeightedAverage": 182.829315837285,
      "FarePerDistanceUnit": 0.09582299479414724,
      "SectorLengthNM": 1030.23218055597,
      "GovernmentTaxes": 0,
      "WeightedAverageGovernmentTaxes": 0,
      "CabinTypeId": 1,
      "CabinTypeName": "Economy"
    },
    {
      "Date": "2021-12-01T00:00:00",
      "Carrier": "British Airways",
      "CarrierId": 290,
      "CarrierCode": null,
      "OriginAirport": "Manchester International ",
      "OriginAirportId": 1975,
      "OriginAirportCode": null,
      "OriginCity": null,
      "OriginCityId": 0,
      "OriginCityCode": null,
      "OriginCountry": null,
      "OriginCountryId": 0,
      "OriginCountryCode": null,
      "OriginContinent": null,
      "OriginContinentId": 0,
      "OriginContinentCode": null,
      "DestinationAirport": "Europe",
      "DestinationAirportId": 0,
      "DestinationAirportCode": null,
      "DestinationCity": null,
      "DestinationCityId": 0,
      "DestinationCityCode": null,
      "DestinationCountry": null,
      "DestinationCountryId": 0,
      "DestinationCountryCode": null,
      "DestinationContinent": null,
      "DestinationContinentId": 0,
      "DestinationContinentCode": null,
      "SectorLength": 254.61,
      "Frequency": 0,
      "SixMonthsFare": 50.52610854961895,
      "ThreeMonthsFare": 48.7945485192191,
      "OneMonthFare": 92.6475850293842,
      "OneWeekFare": 105.6284054474745,
      "ForecastFare": null,
      "SixMonthDyf": null,
      "ThreeMonthDyf": null,
      "OneMonthDyf": null,
      "PublishedAirlineResult": null,
      "TotalCount": null,
      "WeightedAverage": 94.752691587413,
      "FarePerDistanceUnit": 0.37214835076160796,
      "SectorLengthNM": 137.47840161183,
      "GovernmentTaxes": 0,
      "WeightedAverageGovernmentTaxes": 0,
      "CabinTypeId": 1,
      "CabinTypeName": "Economy"
    },
    {
      "Date": "2021-12-01T00:00:00",
      "Carrier": "Air Baltic",
      "CarrierId": 317,
      "CarrierCode": null,
      "OriginAirport": "Manchester International ",
      "OriginAirportId": 1975,
      "OriginAirportCode": null,
      "OriginCity": null,
      "OriginCityId": 0,
      "OriginCityCode": null,
      "OriginCountry": null,
      "OriginCountryId": 0,
      "OriginCountryCode": null,
      "OriginContinent": null,
      "OriginContinentId": 0,
      "OriginContinentCode": null,
      "DestinationAirport": "Europe",
      "DestinationAirportId": 0,
      "DestinationAirportCode": null,
      "DestinationCity": null,
      "DestinationCityId": 0,
      "DestinationCityCode": null,
      "DestinationCountry": null,
      "DestinationCountryId": 0,
      "DestinationCountryCode": null,
      "DestinationContinent": null,
      "DestinationContinentId": 0,
      "DestinationContinentCode": null,
      "SectorLength": 1794.25,
      "Frequency": 0,
      "SixMonthsFare": null,
      "ThreeMonthsFare": 64.87529996593194,
      "OneMonthFare": 68.994687537335,
      "OneWeekFare": 75.0356670301783,
      "ForecastFare": null,
      "SixMonthDyf": null,
      "ThreeMonthDyf": null,
      "OneMonthDyf": null,
      "PublishedAirlineResult": null,
      "TotalCount": null,
      "WeightedAverage": 71.60323852661635,
      "FarePerDistanceUnit": 0.039907057838437426,
      "SectorLengthNM": 968.81749378275,
      "GovernmentTaxes": 0,
      "WeightedAverageGovernmentTaxes": 0,
      "CabinTypeId": 1,
      "CabinTypeName": "Economy"
    },
    {
      "Date": "2021-12-01T00:00:00",
      "Carrier": "Norwegian Air Shuttle",
      "CarrierId": 395,
      "CarrierCode": null,
      "OriginAirport": "Manchester International ",
      "OriginAirportId": 1975,
      "OriginAirportCode": null,
      "OriginCity": null,
      "OriginCityId": 0,
      "OriginCityCode": null,
      "OriginCountry": null,
      "OriginCountryId": 0,
      "OriginCountryCode": null,
      "OriginContinent": null,
      "OriginContinentId": 0,
      "OriginContinentCode": null,
      "DestinationAirport": "Europe",
      "DestinationAirportId": 0,
      "DestinationAirportCode": null,
      "DestinationCity": null,
      "DestinationCityId": 0,
      "DestinationCityCode": null,
      "DestinationCountry": null,
      "DestinationCountryId": 0,
      "DestinationCountryCode": null,
      "DestinationContinent": null,
      "DestinationContinentId": 0,
      "DestinationContinentCode": null,
      "SectorLength": 1120.633571,
      "Frequency": 0,
      "SixMonthsFare": 128.65838046304,
      "ThreeMonthsFare": 91.7456656021878,
      "OneMonthFare": 100.83629182919096,
      "OneWeekFare": 86.96338262836996,
      "ForecastFare": null,
      "SixMonthDyf": null,
      "ThreeMonthDyf": null,
      "OneMonthDyf": null,
      "PublishedAirlineResult": null,
      "TotalCount": null,
      "WeightedAverage": 92.9907746060802,
      "FarePerDistanceUnit": 0.08298053620069552,
      "SectorLengthNM": 605.0937203316336,
      "GovernmentTaxes": 0,
      "WeightedAverageGovernmentTaxes": 0,
      "CabinTypeId": 1,
      "CabinTypeName": "Economy"
    },
    {
      "Date": "2021-12-01T00:00:00",
      "Carrier": "Aer Lingus",
      "CarrierId": 416,
      "CarrierCode": null,
      "OriginAirport": "Manchester International ",
      "OriginAirportId": 1975,
      "OriginAirportCode": null,
      "OriginCity": null,
      "OriginCityId": 0,
      "OriginCityCode": null,
      "OriginCountry": null,
      "OriginCountryId": 0,
      "OriginCountryCode": null,
      "OriginContinent": null,
      "OriginContinentId": 0,
      "OriginContinentCode": null,
      "DestinationAirport": "Europe",
      "DestinationAirportId": 0,
      "DestinationAirportCode": null,
      "DestinationCity": null,
      "DestinationCityId": 0,
      "DestinationCityCode": null,
      "DestinationCountry": null,
      "DestinationCountryId": 0,
      "DestinationCountryCode": null,
      "DestinationContinent": null,
      "DestinationContinentId": 0,
      "DestinationContinentCode": null,
      "SectorLength": 283.095352,
      "Frequency": 0,
      "SixMonthsFare": 46.90083985830905,
      "ThreeMonthsFare": 61.20648432627595,
      "OneMonthFare": 50.9729571884702,
      "OneWeekFare": 61.90337695395995,
      "ForecastFare": null,
      "SixMonthDyf": null,
      "ThreeMonthDyf": null,
      "OneMonthDyf": null,
      "PublishedAirlineResult": null,
      "TotalCount": null,
      "WeightedAverage": 57.4615197849957,
      "FarePerDistanceUnit": 0.20297585028875959,
      "SectorLengthNM": 152.85926121007967,
      "GovernmentTaxes": 0,
      "WeightedAverageGovernmentTaxes": 0,
      "CabinTypeId": 1,
      "CabinTypeName": "Economy"
    },
    {
      "Date": "2021-12-01T00:00:00",
      "Carrier": "Eurowings",
      "CarrierId": 432,
      "CarrierCode": null,
      "OriginAirport": "Manchester International ",
      "OriginAirportId": 1975,
      "OriginAirportCode": null,
      "OriginCity": null,
      "OriginCityId": 0,
      "OriginCityCode": null,
      "OriginCountry": null,
      "OriginCountryId": 0,
      "OriginCountryCode": null,
      "OriginContinent": null,
      "OriginContinentId": 0,
      "OriginContinentCode": null,
      "DestinationAirport": "Europe",
      "DestinationAirportId": 0,
      "DestinationAirportCode": null,
      "DestinationCity": null,
      "DestinationCityId": 0,
      "DestinationCityCode": null,
      "DestinationCountry": null,
      "DestinationCountryId": 0,
      "DestinationCountryCode": null,
      "DestinationContinent": null,
      "DestinationContinentId": 0,
      "DestinationContinentCode": null,
      "SectorLength": 690.2,
      "Frequency": 0,
      "SixMonthsFare": 61.48352612252365,
      "ThreeMonthsFare": 39.89790275077675,
      "OneMonthFare": 61.25319938758795,
      "OneWeekFare": 109.7991772267035,
      "ForecastFare": null,
      "SixMonthDyf": null,
      "ThreeMonthDyf": null,
      "OneMonthDyf": null,
      "PublishedAirlineResult": null,
      "TotalCount": null,
      "WeightedAverage": 83.39065864346455,
      "FarePerDistanceUnit": 0.12082100643793763,
      "SectorLengthNM": 372.6781854306,
      "GovernmentTaxes": 0,
      "WeightedAverageGovernmentTaxes": 0,
      "CabinTypeId": 1,
      "CabinTypeName": "Economy"
    },
    {
      "Date": "2021-12-01T00:00:00",
      "Carrier": "Ryanair",
      "CarrierId": 464,
      "CarrierCode": null,
      "OriginAirport": "Manchester International ",
      "OriginAirportId": 1975,
      "OriginAirportCode": null,
      "OriginCity": null,
      "OriginCityId": 0,
      "OriginCityCode": null,
      "OriginCountry": null,
      "OriginCountryId": 0,
      "OriginCountryCode": null,
      "OriginContinent": null,
      "OriginContinentId": 0,
      "OriginContinentCode": null,
      "DestinationAirport": "Europe",
      "DestinationAirportId": 0,
      "DestinationAirportCode": null,
      "DestinationCity": null,
      "DestinationCityId": 0,
      "DestinationCityCode": null,
      "DestinationCountry": null,
      "DestinationCountryId": 0,
      "DestinationCountryCode": null,
      "DestinationContinent": null,
      "DestinationContinentId": 0,
      "DestinationContinentCode": null,
      "SectorLength": 1446.576164,
      "Frequency": 0,
      "SixMonthsFare": 43.01916741871975,
      "ThreeMonthsFare": 37.07974277648335,
      "OneMonthFare": 23.80915432835115,
      "OneWeekFare": 14.18378020402525,
      "ForecastFare": null,
      "SixMonthDyf": null,
      "ThreeMonthDyf": null,
      "OneMonthDyf": null,
      "PublishedAirlineResult": null,
      "TotalCount": null,
      "WeightedAverage": 20.3235261110014,
      "FarePerDistanceUnit": 0.01404939927587622,
      "SectorLengthNM": 781.0886408094437,
      "GovernmentTaxes": 0,
      "WeightedAverageGovernmentTaxes": 0,
      "CabinTypeId": 1,
      "CabinTypeName": "Economy"
    },
    {
      "Date": "2021-12-01T00:00:00",
      "Carrier": "Aurigny Air Services",
      "CarrierId": 504,
      "CarrierCode": null,
      "OriginAirport": "Manchester International ",
      "OriginAirportId": 1975,
      "OriginAirportCode": null,
      "OriginCity": null,
      "OriginCityId": 0,
      "OriginCityCode": null,
      "OriginCountry": null,
      "OriginCountryId": 0,
      "OriginCountryCode": null,
      "OriginContinent": null,
      "OriginContinentId": 0,
      "OriginContinentCode": null,
      "DestinationAirport": "Europe",
      "DestinationAirportId": 0,
      "DestinationAirportCode": null,
      "DestinationCity": null,
      "DestinationCityId": 0,
      "DestinationCityCode": null,
      "DestinationCountry": null,
      "DestinationCountryId": 0,
      "DestinationCountryCode": null,
      "DestinationContinent": null,
      "DestinationContinentId": 0,
      "DestinationContinentCode": null,
      "SectorLength": 458.42,
      "Frequency": 0,
      "SixMonthsFare": null,
      "ThreeMonthsFare": 64.7168900075911,
      "OneMonthFare": 70.1569712376258,
      "OneWeekFare": 71.9904090202934,
      "ForecastFare": null,
      "SixMonthDyf": null,
      "ThreeMonthDyf": null,
      "OneMonthDyf": null,
      "PublishedAirlineResult": null,
      "TotalCount": null,
      "WeightedAverage": 70.5296820059561,
      "FarePerDistanceUnit": 0.15385385019404935,
      "SectorLengthNM": 247.52699763126,
      "GovernmentTaxes": 0,
      "WeightedAverageGovernmentTaxes": 0,
      "CabinTypeId": 1,
      "CabinTypeName": "Economy"
    },
    {
      "Date": "2021-12-01T00:00:00",
      "Carrier": "Iberia",
      "CarrierId": 564,
      "CarrierCode": null,
      "OriginAirport": "Manchester International ",
      "OriginAirportId": 1975,
      "OriginAirportCode": null,
      "OriginCity": null,
      "OriginCityId": 0,
      "OriginCityCode": null,
      "OriginCountry": null,
      "OriginCountryId": 0,
      "OriginCountryCode": null,
      "OriginContinent": null,
      "OriginContinentId": 0,
      "OriginContinentCode": null,
      "DestinationAirport": "Europe",
      "DestinationAirportId": 0,
      "DestinationAirportCode": null,
      "DestinationCity": null,
      "DestinationCityId": 0,
      "DestinationCityCode": null,
      "DestinationCountry": null,
      "DestinationCountryId": 0,
      "DestinationCountryCode": null,
      "DestinationContinent": null,
      "DestinationContinentId": 0,
      "DestinationContinentCode": null,
      "SectorLength": 1504.6,
      "Frequency": 0,
      "SixMonthsFare": 53.06465570194615,
      "ThreeMonthsFare": 56.56091782814805,
      "OneMonthFare": 100.48239522805984,
      "OneWeekFare": 83.7169883303244,
      "ForecastFare": null,
      "SixMonthDyf": null,
      "ThreeMonthDyf": null,
      "OneMonthDyf": null,
      "PublishedAirlineResult": null,
      "TotalCount": null,
      "WeightedAverage": 87.70754403920115,
      "FarePerDistanceUnit": 0.058292931037618734,
      "SectorLengthNM": 812.4190057938,
      "GovernmentTaxes": 0,
      "WeightedAverageGovernmentTaxes": 0,
      "CabinTypeId": 1,
      "CabinTypeName": "Economy"
    },
    {
      "Date": "2021-12-01T00:00:00",
      "Carrier": "KLM",
      "CarrierId": 652,
      "CarrierCode": null,
      "OriginAirport": "Manchester International ",
      "OriginAirportId": 1975,
      "OriginAirportCode": null,
      "OriginCity": null,
      "OriginCityId": 0,
      "OriginCityCode": null,
      "OriginCountry": null,
      "OriginCountryId": 0,
      "OriginCountryCode": null,
      "OriginContinent": null,
      "OriginContinentId": 0,
      "OriginContinentCode": null,
      "DestinationAirport": "Europe",
      "DestinationAirportId": 0,
      "DestinationAirportCode": null,
      "DestinationCity": null,
      "DestinationCityId": 0,
      "DestinationCityCode": null,
      "DestinationCountry": null,
      "DestinationCountryId": 0,
      "DestinationCountryCode": null,
      "DestinationContinent": null,
      "DestinationContinentId": 0,
      "DestinationContinentCode": null,
      "SectorLength": 512.68,
      "Frequency": 0,
      "SixMonthsFare": 55.20803138555235,
      "ThreeMonthsFare": 51.88140203175365,
      "OneMonthFare": 78.8910666350665,
      "OneWeekFare": 74.36885321211425,
      "ForecastFare": null,
      "SixMonthDyf": null,
      "ThreeMonthDyf": null,
      "OneMonthDyf": null,
      "PublishedAirlineResult": null,
      "TotalCount": null,
      "WeightedAverage": 73.9289934632591,
      "FarePerDistanceUnit": 0.14420104834060057,
      "SectorLengthNM": 276.82505376204,
      "GovernmentTaxes": 0,
      "WeightedAverageGovernmentTaxes": 0,
      "CabinTypeId": 1,
      "CabinTypeName": "Economy"
    },
    {
      "Date": "2021-12-01T00:00:00",
      "Carrier": "Lufthansa",
      "CarrierId": 684,
      "CarrierCode": null,
      "OriginAirport": "Manchester International ",
      "OriginAirportId": 1975,
      "OriginAirportCode": null,
      "OriginCity": null,
      "OriginCityId": 0,
      "OriginCityCode": null,
      "OriginCountry": null,
      "OriginCountryId": 0,
      "OriginCountryCode": null,
      "OriginContinent": null,
      "OriginContinentId": 0,
      "OriginContinentCode": null,
      "DestinationAirport": "Europe",
      "DestinationAirportId": 0,
      "DestinationAirportCode": null,
      "DestinationCity": null,
      "DestinationCityId": 0,
      "DestinationCityCode": null,
      "DestinationCountry": null,
      "DestinationCountryId": 0,
      "DestinationCountryCode": null,
      "DestinationContinent": null,
      "DestinationContinentId": 0,
      "DestinationContinentCode": null,
      "SectorLength": 1007.455162,
      "Frequency": 0,
      "SixMonthsFare": 59.79687754741705,
      "ThreeMonthsFare": 73.51251551995095,
      "OneMonthFare": 93.82222478050925,
      "OneWeekFare": 113.9740449271825,
      "ForecastFare": null,
      "SixMonthDyf": null,
      "ThreeMonthDyf": null,
      "OneMonthDyf": null,
      "PublishedAirlineResult": null,
      "TotalCount": null,
      "WeightedAverage": 101.86716392778985,
      "FarePerDistanceUnit": 0.10111334754150562,
      "SectorLengthNM": 543.9822684393671,
      "GovernmentTaxes": 0,
      "WeightedAverageGovernmentTaxes": 0,
      "CabinTypeId": 1,
      "CabinTypeName": "Economy"
    },
    {
      "Date": "2021-12-01T00:00:00",
      "Carrier": "Jet2",
      "CarrierId": 698,
      "CarrierCode": null,
      "OriginAirport": "Manchester International ",
      "OriginAirportId": 1975,
      "OriginAirportCode": null,
      "OriginCity": null,
      "OriginCityId": 0,
      "OriginCityCode": null,
      "OriginCountry": null,
      "OriginCountryId": 0,
      "OriginCountryCode": null,
      "OriginContinent": null,
      "OriginContinentId": 0,
      "OriginContinentCode": null,
      "DestinationAirport": "Europe",
      "DestinationAirportId": 0,
      "DestinationAirportCode": null,
      "DestinationCity": null,
      "DestinationCityId": 0,
      "DestinationCityCode": null,
      "DestinationCountry": null,
      "DestinationCountryId": 0,
      "DestinationCountryCode": null,
      "DestinationContinent": null,
      "DestinationContinentId": 0,
      "DestinationContinentCode": null,
      "SectorLength": 2462.888871,
      "Frequency": 0,
      "SixMonthsFare": 96.93914604073275,
      "ThreeMonthsFare": 63.67652190281175,
      "OneMonthFare": 55.49139396173275,
      "OneWeekFare": 42.0024403663483,
      "ForecastFare": null,
      "SixMonthDyf": null,
      "ThreeMonthDyf": null,
      "OneMonthDyf": null,
      "PublishedAirlineResult": null,
      "TotalCount": null,
      "WeightedAverage": 49.56542995814845,
      "FarePerDistanceUnit": 0.020124915314601075,
      "SectorLengthNM": 1329.8536009294394,
      "GovernmentTaxes": 0,
      "WeightedAverageGovernmentTaxes": 0,
      "CabinTypeId": 1,
      "CabinTypeName": "Economy"
    },
    {
      "Date": "2021-12-01T00:00:00",
      "Carrier": "SWISS",
      "CarrierId": 703,
      "CarrierCode": null,
      "OriginAirport": "Manchester International ",
      "OriginAirportId": 1975,
      "OriginAirportCode": null,
      "OriginCity": null,
      "OriginCityId": 0,
      "OriginCityCode": null,
      "OriginCountry": null,
      "OriginCountryId": 0,
      "OriginCountryCode": null,
      "OriginContinent": null,
      "OriginContinentId": 0,
      "OriginContinentCode": null,
      "DestinationAirport": "Europe",
      "DestinationAirportId": 0,
      "DestinationAirportCode": null,
      "DestinationCity": null,
      "DestinationCityId": 0,
      "DestinationCityCode": null,
      "DestinationCountry": null,
      "DestinationCountryId": 0,
      "DestinationCountryCode": null,
      "DestinationContinent": null,
      "DestinationContinentId": 0,
      "DestinationContinentCode": null,
      "SectorLength": 1059.04,
      "Frequency": 0,
      "SixMonthsFare": 76.4484978293053,
      "ThreeMonthsFare": 101.33955983591456,
      "OneMonthFare": 125.0812389433385,
      "OneWeekFare": 146.9836038327605,
      "ForecastFare": null,
      "SixMonthDyf": null,
      "ThreeMonthDyf": null,
      "OneMonthDyf": null,
      "PublishedAirlineResult": null,
      "TotalCount": null,
      "WeightedAverage": 133.6582534773075,
      "FarePerDistanceUnit": 0.1262069926322967,
      "SectorLengthNM": 571.83585264912,
      "GovernmentTaxes": 0,
      "WeightedAverageGovernmentTaxes": 0,
      "CabinTypeId": 1,
      "CabinTypeName": "Economy"
    },
    {
      "Date": "2021-12-01T00:00:00",
      "Carrier": "Austrian",
      "CarrierId": 817,
      "CarrierCode": null,
      "OriginAirport": "Manchester International ",
      "OriginAirportId": 1975,
      "OriginAirportCode": null,
      "OriginCity": null,
      "OriginCityId": 0,
      "OriginCityCode": null,
      "OriginCountry": null,
      "OriginCountryId": 0,
      "OriginCountryCode": null,
      "OriginContinent": null,
      "OriginContinentId": 0,
      "OriginContinentCode": null,
      "DestinationAirport": "Europe",
      "DestinationAirportId": 0,
      "DestinationAirportCode": null,
      "DestinationCity": null,
      "DestinationCityId": 0,
      "DestinationCityCode": null,
      "DestinationCountry": null,
      "DestinationCountryId": 0,
      "DestinationCountryCode": null,
      "DestinationContinent": null,
      "DestinationContinentId": 0,
      "DestinationContinentCode": null,
      "SectorLength": 1519.97,
      "Frequency": 0,
      "SixMonthsFare": null,
      "ThreeMonthsFare": 81.2514645781995,
      "OneMonthFare": 93.19054967769544,
      "OneWeekFare": 99.6058449760424,
      "ForecastFare": null,
      "SixMonthDyf": null,
      "ThreeMonthDyf": null,
      "OneMonthDyf": null,
      "PublishedAirlineResult": null,
      "TotalCount": null,
      "WeightedAverage": 95.20428881691915,
      "FarePerDistanceUnit": 0.06263563676711985,
      "SectorLengthNM": 820.71814185591,
      "GovernmentTaxes": 0,
      "WeightedAverageGovernmentTaxes": 0,
      "CabinTypeId": 1,
      "CabinTypeName": "Economy"
    },
    {
      "Date": "2021-12-01T00:00:00",
      "Carrier": "Blue Islands",
      "CarrierId": 971,
      "CarrierCode": null,
      "OriginAirport": "Manchester International ",
      "OriginAirportId": 1975,
      "OriginAirportCode": null,
      "OriginCity": null,
      "OriginCityId": 0,
      "OriginCityCode": null,
      "OriginCountry": null,
      "OriginCountryId": 0,
      "OriginCountryCode": null,
      "OriginContinent": null,
      "OriginContinentId": 0,
      "OriginContinentCode": null,
      "DestinationAirport": "Europe",
      "DestinationAirportId": 0,
      "DestinationAirportCode": null,
      "DestinationCity": null,
      "DestinationCityId": 0,
      "DestinationCityCode": null,
      "DestinationCountry": null,
      "DestinationCountryId": 0,
      "DestinationCountryCode": null,
      "DestinationContinent": null,
      "DestinationContinentId": 0,
      "DestinationContinentCode": null,
      "SectorLength": 316.8,
      "Frequency": 0,
      "SixMonthsFare": null,
      "ThreeMonthsFare": 47.1076965303999,
      "OneMonthFare": 68.3244655495761,
      "OneWeekFare": 91.82068746960014,
      "ForecastFare": null,
      "SixMonthDyf": null,
      "ThreeMonthDyf": null,
      "OneMonthDyf": null,
      "PublishedAirlineResult": null,
      "TotalCount": null,
      "WeightedAverage": 77.9508996076705,
      "FarePerDistanceUnit": 0.24605713259997,
      "SectorLengthNM": 171.0583151904,
      "GovernmentTaxes": 0,
      "WeightedAverageGovernmentTaxes": 0,
      "CabinTypeId": 1,
      "CabinTypeName": "Economy"
    },
    {
      "Date": "2021-12-01T00:00:00",
      "Carrier": "SAS",
      "CarrierId": 974,
      "CarrierCode": null,
      "OriginAirport": "Manchester International ",
      "OriginAirportId": 1975,
      "OriginAirportCode": null,
      "OriginCity": null,
      "OriginCityId": 0,
      "OriginCityCode": null,
      "OriginCountry": null,
      "OriginCountryId": 0,
      "OriginCountryCode": null,
      "OriginContinent": null,
      "OriginContinentId": 0,
      "OriginContinentCode": null,
      "DestinationAirport": "Europe",
      "DestinationAirportId": 0,
      "DestinationAirportCode": null,
      "DestinationCity": null,
      "DestinationCityId": 0,
      "DestinationCityCode": null,
      "DestinationCountry": null,
      "DestinationCountryId": 0,
      "DestinationCountryCode": null,
      "DestinationContinent": null,
      "DestinationContinentId": 0,
      "DestinationContinentCode": null,
      "SectorLength": 1214.98375,
      "Frequency": 0,
      "SixMonthsFare": 83.35186419062755,
      "ThreeMonthsFare": 95.03623493277026,
      "OneMonthFare": 133.2381162585995,
      "OneWeekFare": 143.7359657054825,
      "ForecastFare": null,
      "SixMonthDyf": null,
      "ThreeMonthDyf": null,
      "OneMonthDyf": null,
      "PublishedAirlineResult": null,
      "TotalCount": null,
      "WeightedAverage": 134.666852849458,
      "FarePerDistanceUnit": 0.11083839833204188,
      "SectorLengthNM": 656.0387413469513,
      "GovernmentTaxes": 0,
      "WeightedAverageGovernmentTaxes": 0,
      "CabinTypeId": 1,
      "CabinTypeName": "Economy"
    },
    {
      "Date": "2021-12-01T00:00:00",
      "Carrier": "Brussels Airlines",
      "CarrierId": 977,
      "CarrierCode": null,
      "OriginAirport": "Manchester International ",
      "OriginAirportId": 1975,
      "OriginAirportCode": null,
      "OriginCity": null,
      "OriginCityId": 0,
      "OriginCityCode": null,
      "OriginCountry": null,
      "OriginCountryId": 0,
      "OriginCountryCode": null,
      "OriginContinent": null,
      "OriginContinentId": 0,
      "OriginContinentCode": null,
      "DestinationAirport": "Europe",
      "DestinationAirportId": 0,
      "DestinationAirportCode": null,
      "DestinationCity": null,
      "DestinationCityId": 0,
      "DestinationCityCode": null,
      "DestinationCountry": null,
      "DestinationCountryId": 0,
      "DestinationCountryCode": null,
      "DestinationContinent": null,
      "DestinationContinentId": 0,
      "DestinationContinentCode": null,
      "SectorLength": 563.86,
      "Frequency": 0,
      "SixMonthsFare": null,
      "ThreeMonthsFare": 59.7376796954167,
      "OneMonthFare": 62.08885591662915,
      "OneWeekFare": 95.4563093056692,
      "ForecastFare": null,
      "SixMonthDyf": null,
      "ThreeMonthDyf": null,
      "OneMonthDyf": null,
      "PublishedAirlineResult": null,
      "TotalCount": null,
      "WeightedAverage": 78.53746498902795,
      "FarePerDistanceUnit": 0.1392853988384137,
      "SectorLengthNM": 304.46004293958,
      "GovernmentTaxes": 0,
      "WeightedAverageGovernmentTaxes": 0,
      "CabinTypeId": 1,
      "CabinTypeName": "Economy"
    },
    {
      "Date": "2021-12-01T00:00:00",
      "Carrier": "Eastern Airways",
      "CarrierId": 995,
      "CarrierCode": null,
      "OriginAirport": "Manchester International ",
      "OriginAirportId": 1975,
      "OriginAirportCode": null,
      "OriginCity": null,
      "OriginCityId": 0,
      "OriginCityCode": null,
      "OriginCountry": null,
      "OriginCountryId": 0,
      "OriginCountryCode": null,
      "OriginContinent": null,
      "OriginContinentId": 0,
      "OriginContinentCode": null,
      "DestinationAirport": "Europe",
      "DestinationAirportId": 0,
      "DestinationAirportCode": null,
      "DestinationCity": null,
      "DestinationCityId": 0,
      "DestinationCityCode": null,
      "DestinationCountry": null,
      "DestinationCountryId": 0,
      "DestinationCountryCode": null,
      "DestinationContinent": null,
      "DestinationContinentId": 0,
      "DestinationContinentCode": null,
      "SectorLength": 288.44,
      "Frequency": 0,
      "SixMonthsFare": null,
      "ThreeMonthsFare": 80.48938423807304,
      "OneMonthFare": 85.48723872978255,
      "OneWeekFare": 93.8253761455636,
      "ForecastFare": null,
      "SixMonthDyf": null,
      "ThreeMonthDyf": null,
      "OneMonthDyf": null,
      "PublishedAirlineResult": null,
      "TotalCount": null,
      "WeightedAverage": 89.156521988502,
      "FarePerDistanceUnit": 0.3090990222871377,
      "SectorLengthNM": 155.74514025732,
      "GovernmentTaxes": 0,
      "WeightedAverageGovernmentTaxes": 0,
      "CabinTypeId": 1,
      "CabinTypeName": "Economy"
    },
    {
      "Date": "2021-12-01T00:00:00",
      "Carrier": "TAP Air Portugal",
      "CarrierId": 1024,
      "CarrierCode": null,
      "OriginAirport": "Manchester International ",
      "OriginAirportId": 1975,
      "OriginAirportCode": null,
      "OriginCity": null,
      "OriginCityId": 0,
      "OriginCityCode": null,
      "OriginCountry": null,
      "OriginCountryId": 0,
      "OriginCountryCode": null,
      "OriginContinent": null,
      "OriginContinentId": 0,
      "OriginContinentCode": null,
      "DestinationAirport": "Europe",
      "DestinationAirportId": 0,
      "DestinationAirportCode": null,
      "DestinationCity": null,
      "DestinationCityId": 0,
      "DestinationCityCode": null,
      "DestinationCountry": null,
      "DestinationCountryId": 0,
      "DestinationCountryCode": null,
      "DestinationContinent": null,
      "DestinationContinentId": 0,
      "DestinationContinentCode": null,
      "SectorLength": 1788.45,
      "Frequency": 0,
      "SixMonthsFare": 70.6540814020813,
      "ThreeMonthsFare": 85.3059032416812,
      "OneMonthFare": 118.59111463149554,
      "OneWeekFare": 128.962641857946,
      "ForecastFare": null,
      "SixMonthDyf": null,
      "ThreeMonthDyf": null,
      "OneMonthDyf": null,
      "PublishedAirlineResult": null,
      "TotalCount": null,
      "WeightedAverage": 120.44835710573935,
      "FarePerDistanceUnit": 0.06734790299183055,
      "SectorLengthNM": 965.68574432535,
      "GovernmentTaxes": 0,
      "WeightedAverageGovernmentTaxes": 0,
      "CabinTypeId": 1,
      "CabinTypeName": "Economy"
    },
    {
      "Date": "2021-12-01T00:00:00",
      "Carrier": "easyJet",
      "CarrierId": 1038,
      "CarrierCode": null,
      "OriginAirport": "Manchester International ",
      "OriginAirportId": 1975,
      "OriginAirportCode": null,
      "OriginCity": null,
      "OriginCityId": 0,
      "OriginCityCode": null,
      "OriginCountry": null,
      "OriginCountryId": 0,
      "OriginCountryCode": null,
      "OriginContinent": null,
      "OriginContinentId": 0,
      "OriginContinentCode": null,
      "DestinationAirport": "Europe",
      "DestinationAirportId": 0,
      "DestinationAirportCode": null,
      "DestinationCity": null,
      "DestinationCityId": 0,
      "DestinationCityCode": null,
      "DestinationCountry": null,
      "DestinationCountryId": 0,
      "DestinationCountryCode": null,
      "DestinationContinent": null,
      "DestinationContinentId": 0,
      "DestinationContinentCode": null,
      "SectorLength": 1301.82253,
      "Frequency": 0,
      "SixMonthsFare": 42.05337013283935,
      "ThreeMonthsFare": 34.63240448666685,
      "OneMonthFare": 44.28769572543,
      "OneWeekFare": 37.896476952839,
      "ForecastFare": null,
      "SixMonthDyf": null,
      "ThreeMonthDyf": null,
      "OneMonthDyf": null,
      "PublishedAirlineResult": null,
      "TotalCount": null,
      "WeightedAverage": 40.1265572152582,
      "FarePerDistanceUnit": 0.0308233697685799,
      "SectorLengthNM": 702.9279313721715,
      "GovernmentTaxes": 0,
      "WeightedAverageGovernmentTaxes": 0,
      "CabinTypeId": 1,
      "CabinTypeName": "Economy"
    },
    {
      "Date": "2021-12-01T00:00:00",
      "Carrier": "Vueling",
      "CarrierId": 1118,
      "CarrierCode": null,
      "OriginAirport": "Manchester International ",
      "OriginAirportId": 1975,
      "OriginAirportCode": null,
      "OriginCity": null,
      "OriginCityId": 0,
      "OriginCityCode": null,
      "OriginCountry": null,
      "OriginCountryId": 0,
      "OriginCountryCode": null,
      "OriginContinent": null,
      "OriginContinentId": 0,
      "OriginContinentCode": null,
      "DestinationAirport": "Europe",
      "DestinationAirportId": 0,
      "DestinationAirportCode": null,
      "DestinationCity": null,
      "DestinationCityId": 0,
      "DestinationCityCode": null,
      "DestinationCountry": null,
      "DestinationCountryId": 0,
      "DestinationCountryCode": null,
      "DestinationContinent": null,
      "DestinationContinentId": 0,
      "DestinationContinentCode": null,
      "SectorLength": 1448.54,
      "Frequency": 0,
      "SixMonthsFare": null,
      "ThreeMonthsFare": 32.85508162994535,
      "OneMonthFare": 51.95492978526155,
      "OneWeekFare": 43.10080653321165,
      "ForecastFare": null,
      "SixMonthDyf": null,
      "ThreeMonthDyf": null,
      "OneMonthDyf": null,
      "PublishedAirlineResult": null,
      "TotalCount": null,
      "WeightedAverage": 45.61788334370495,
      "FarePerDistanceUnit": 0.0314923187096697,
      "SectorLengthNM": 782.14902741762,
      "GovernmentTaxes": 0,
      "WeightedAverageGovernmentTaxes": 0,
      "CabinTypeId": 1,
      "CabinTypeName": "Economy"
    },
    {
      "Date": "2021-12-01T00:00:00",
      "Carrier": "SunExpress",
      "CarrierId": 1181,
      "CarrierCode": null,
      "OriginAirport": "Manchester International ",
      "OriginAirportId": 1975,
      "OriginAirportCode": null,
      "OriginCity": null,
      "OriginCityId": 0,
      "OriginCityCode": null,
      "OriginCountry": null,
      "OriginCountryId": 0,
      "OriginCountryCode": null,
      "OriginContinent": null,
      "OriginContinentId": 0,
      "OriginContinentCode": null,
      "DestinationAirport": "Europe",
      "DestinationAirportId": 0,
      "DestinationAirportCode": null,
      "DestinationCity": null,
      "DestinationCityId": 0,
      "DestinationCityCode": null,
      "DestinationCountry": null,
      "DestinationCountryId": 0,
      "DestinationCountryCode": null,
      "DestinationContinent": null,
      "DestinationContinentId": 0,
      "DestinationContinentCode": null,
      "SectorLength": 3292.37,
      "Frequency": 0,
      "SixMonthsFare": null,
      "ThreeMonthsFare": 77.38540532463675,
      "OneMonthFare": 74.13164213971515,
      "OneWeekFare": 106.1678026124053,
      "ForecastFare": null,
      "SixMonthDyf": null,
      "ThreeMonthDyf": null,
      "OneMonthDyf": null,
      "PublishedAirlineResult": null,
      "TotalCount": null,
      "WeightedAverage": 90.47509869455244,
      "FarePerDistanceUnit": 0.02748023420652978,
      "SectorLengthNM": 1777.73757949311,
      "GovernmentTaxes": 0,
      "WeightedAverageGovernmentTaxes": 0,
      "CabinTypeId": 1,
      "CabinTypeName": "Economy"
    },
    {
      "Date": "2021-12-01T00:00:00",
      "Carrier": "Loganair",
      "CarrierId": 1516,
      "CarrierCode": null,
      "OriginAirport": "Manchester International ",
      "OriginAirportId": 1975,
      "OriginAirportCode": null,
      "OriginCity": null,
      "OriginCityId": 0,
      "OriginCityCode": null,
      "OriginCountry": null,
      "OriginCountryId": 0,
      "OriginCountryCode": null,
      "OriginContinent": null,
      "OriginContinentId": 0,
      "OriginContinentCode": null,
      "DestinationAirport": "Europe",
      "DestinationAirportId": 0,
      "DestinationAirportCode": null,
      "DestinationCity": null,
      "DestinationCityId": 0,
      "DestinationCityCode": null,
      "DestinationCountry": null,
      "DestinationCountryId": 0,
      "DestinationCountryCode": null,
      "DestinationContinent": null,
      "DestinationContinentId": 0,
      "DestinationContinentCode": null,
      "SectorLength": 373.514309,
      "Frequency": 0,
      "SixMonthsFare": null,
      "ThreeMonthsFare": 74.47744602069285,
      "OneMonthFare": 83.9113335223249,
      "OneWeekFare": 118.6831215102395,
      "ForecastFare": null,
      "SixMonthDyf": null,
      "ThreeMonthDyf": null,
      "OneMonthDyf": null,
      "PublishedAirlineResult": null,
      "TotalCount": null,
      "WeightedAverage": 100.35383876611876,
      "FarePerDistanceUnit": 0.2686746835343295,
      "SectorLengthNM": 201.68159216239414,
      "GovernmentTaxes": 0,
      "WeightedAverageGovernmentTaxes": 0,
      "CabinTypeId": 1,
      "CabinTypeName": "Economy"
    },
    {
      "Date": "2021-12-01T00:00:00",
      "Carrier": "Hop!",
      "CarrierId": 2635,
      "CarrierCode": null,
      "OriginAirport": "Manchester International ",
      "OriginAirportId": 1975,
      "OriginAirportCode": null,
      "OriginCity": null,
      "OriginCityId": 0,
      "OriginCityCode": null,
      "OriginCountry": null,
      "OriginCountryId": 0,
      "OriginCountryCode": null,
      "OriginContinent": null,
      "OriginContinentId": 0,
      "OriginContinentCode": null,
      "DestinationAirport": "Europe",
      "DestinationAirportId": 0,
      "DestinationAirportCode": null,
      "DestinationCity": null,
      "DestinationCityId": 0,
      "DestinationCityCode": null,
      "DestinationCountry": null,
      "DestinationCountryId": 0,
      "DestinationCountryCode": null,
      "DestinationContinent": null,
      "DestinationContinentId": 0,
      "DestinationContinentCode": null,
      "SectorLength": 618.45,
      "Frequency": 0,
      "SixMonthsFare": 71.8567771764495,
      "ThreeMonthsFare": 73.07836699785474,
      "OneMonthFare": 91.47257559514865,
      "OneWeekFare": 99.9626116048155,
      "ForecastFare": null,
      "SixMonthDyf": null,
      "ThreeMonthDyf": null,
      "OneMonthDyf": null,
      "PublishedAirlineResult": null,
      "TotalCount": null,
      "WeightedAverage": 93.8781727402527,
      "FarePerDistanceUnit": 0.15179589738904148,
      "SectorLengthNM": 333.93628481535,
      "GovernmentTaxes": 0,
      "WeightedAverageGovernmentTaxes": 0,
      "CabinTypeId": 1,
      "CabinTypeName": "Economy"
    },
    {
      "Date": "2021-12-01T00:00:00",
      "Carrier": "Malta Air",
      "CarrierId": 4196,
      "CarrierCode": null,
      "OriginAirport": "Manchester International ",
      "OriginAirportId": 1975,
      "OriginAirportCode": null,
      "OriginCity": null,
      "OriginCityId": 0,
      "OriginCityCode": null,
      "OriginCountry": null,
      "OriginCountryId": 0,
      "OriginCountryCode": null,
      "OriginContinent": null,
      "OriginContinentId": 0,
      "OriginContinentCode": null,
      "DestinationAirport": "Europe",
      "DestinationAirportId": 0,
      "DestinationAirportCode": null,
      "DestinationCity": null,
      "DestinationCityId": 0,
      "DestinationCityCode": null,
      "DestinationCountry": null,
      "DestinationCountryId": 0,
      "DestinationCountryCode": null,
      "DestinationContinent": null,
      "DestinationContinentId": 0,
      "DestinationContinentCode": null,
      "SectorLength": 1162.399411,
      "Frequency": 0,
      "SixMonthsFare": 38.3419123294965,
      "ThreeMonthsFare": 35.307707672811,
      "OneMonthFare": 17.5050372010091,
      "OneWeekFare": 19.5764028499102,
      "ForecastFare": null,
      "SixMonthDyf": null,
      "ThreeMonthDyf": null,
      "OneMonthDyf": null,
      "PublishedAirlineResult": null,
      "TotalCount": null,
      "WeightedAverage": 20.32098707263985,
      "FarePerDistanceUnit": 0.017481931666807986,
      "SectorLengthNM": 627.6454697726431,
      "GovernmentTaxes": 0,
      "WeightedAverageGovernmentTaxes": 0,
      "CabinTypeId": 1,
      "CabinTypeName": "Economy"
    },
    // {
    //   "Date": "2021-11-01T00:00:00",
    //   "Carrier": "Air France",
    //   "CarrierId": 255,
    //   "CarrierCode": null,
    //   "OriginAirport": "Manchester International ",
    //   "OriginAirportId": 1975,
    //   "OriginAirportCode": null,
    //   "OriginCity": null,
    //   "OriginCityId": 0,
    //   "OriginCityCode": null,
    //   "OriginCountry": null,
    //   "OriginCountryId": 0,
    //   "OriginCountryCode": null,
    //   "OriginContinent": null,
    //   "OriginContinentId": 0,
    //   "OriginContinentCode": null,
    //   "DestinationAirport": "Europe",
    //   "DestinationAirportId": 0,
    //   "DestinationAirportCode": null,
    //   "DestinationCity": null,
    //   "DestinationCityId": 0,
    //   "DestinationCityCode": null,
    //   "DestinationCountry": null,
    //   "DestinationCountryId": 0,
    //   "DestinationCountryCode": null,
    //   "DestinationContinent": null,
    //   "DestinationContinentId": 0,
    //   "DestinationContinentCode": null,
    //   "SectorLength": 618.45,
    //   "Frequency": 0,
    //   "SixMonthsFare": 68.48450966179445,
    //   "ThreeMonthsFare": 65.69171697786516,
    //   "OneMonthFare": 66.24267142997965,
    //   "OneWeekFare": 68.24386923459245,
    //   "ForecastFare": null,
    //   "SixMonthDyf": null,
    //   "ThreeMonthDyf": null,
    //   "OneMonthDyf": null,
    //   "PublishedAirlineResult": null,
    //   "TotalCount": null,
    //   "WeightedAverage": 67.1881748870746,
    //   "FarePerDistanceUnit": 0.10863962306908335,
    //   "SectorLengthNM": 333.93628481535,
    //   "GovernmentTaxes": 0,
    //   "WeightedAverageGovernmentTaxes": 0,
    //   "CabinTypeId": 1,
    //   "CabinTypeName": "Economy"
    // },
    // {
    //   "Date": "2021-11-01T00:00:00",
    //   "Carrier": "Finnair",
    //   "CarrierId": 278,
    //   "CarrierCode": null,
    //   "OriginAirport": "Manchester International ",
    //   "OriginAirportId": 1975,
    //   "OriginAirportCode": null,
    //   "OriginCity": null,
    //   "OriginCityId": 0,
    //   "OriginCityCode": null,
    //   "OriginCountry": null,
    //   "OriginCountryId": 0,
    //   "OriginCountryCode": null,
    //   "OriginContinent": null,
    //   "OriginContinentId": 0,
    //   "OriginContinentCode": null,
    //   "DestinationAirport": "Europe",
    //   "DestinationAirportId": 0,
    //   "DestinationAirportCode": null,
    //   "DestinationCity": null,
    //   "DestinationCityId": 0,
    //   "DestinationCityCode": null,
    //   "DestinationCountry": null,
    //   "DestinationCountryId": 0,
    //   "DestinationCountryCode": null,
    //   "DestinationContinent": null,
    //   "DestinationContinentId": 0,
    //   "DestinationContinentCode": null,
    //   "SectorLength": 1907.99,
    //   "Frequency": 0,
    //   "SixMonthsFare": 90.53577076106384,
    //   "ThreeMonthsFare": 103.59849503008844,
    //   "OneMonthFare": 93.3226890675105,
    //   "OneWeekFare": 126.20958735311,
    //   "ForecastFare": null,
    //   "SixMonthDyf": null,
    //   "ThreeMonthDyf": null,
    //   "OneMonthDyf": null,
    //   "PublishedAirlineResult": null,
    //   "TotalCount": null,
    //   "WeightedAverage": 110.7937188065677,
    //   "FarePerDistanceUnit": 0.05806829113704354,
    //   "SectorLengthNM": 1030.23218055597,
    //   "GovernmentTaxes": 0,
    //   "WeightedAverageGovernmentTaxes": 0,
    //   "CabinTypeId": 1,
    //   "CabinTypeName": "Economy"
    // },
    // {
    //   "Date": "2021-11-01T00:00:00",
    //   "Carrier": "British Airways",
    //   "CarrierId": 290,
    //   "CarrierCode": null,
    //   "OriginAirport": "Manchester International ",
    //   "OriginAirportId": 1975,
    //   "OriginAirportCode": null,
    //   "OriginCity": null,
    //   "OriginCityId": 0,
    //   "OriginCityCode": null,
    //   "OriginCountry": null,
    //   "OriginCountryId": 0,
    //   "OriginCountryCode": null,
    //   "OriginContinent": null,
    //   "OriginContinentId": 0,
    //   "OriginContinentCode": null,
    //   "DestinationAirport": "Europe",
    //   "DestinationAirportId": 0,
    //   "DestinationAirportCode": null,
    //   "DestinationCity": null,
    //   "DestinationCityId": 0,
    //   "DestinationCityCode": null,
    //   "DestinationCountry": null,
    //   "DestinationCountryId": 0,
    //   "DestinationCountryCode": null,
    //   "DestinationContinent": null,
    //   "DestinationContinentId": 0,
    //   "DestinationContinentCode": null,
    //   "SectorLength": 254.61,
    //   "Frequency": 0,
    //   "SixMonthsFare": null,
    //   "ThreeMonthsFare": 49.86274731973535,
    //   "OneMonthFare": 53.6643591074157,
    //   "OneWeekFare": 83.2390257328697,
    //   "ForecastFare": null,
    //   "SixMonthDyf": null,
    //   "ThreeMonthDyf": null,
    //   "OneMonthDyf": null,
    //   "PublishedAirlineResult": null,
    //   "TotalCount": null,
    //   "WeightedAverage": 68.07153124137464,
    //   "FarePerDistanceUnit": 0.26735607887111523,
    //   "SectorLengthNM": 137.47840161183,
    //   "GovernmentTaxes": 0,
    //   "WeightedAverageGovernmentTaxes": 0,
    //   "CabinTypeId": 1,
    //   "CabinTypeName": "Economy"
    // },
    // {
    //   "Date": "2021-11-01T00:00:00",
    //   "Carrier": "Air Baltic",
    //   "CarrierId": 317,
    //   "CarrierCode": null,
    //   "OriginAirport": "Manchester International ",
    //   "OriginAirportId": 1975,
    //   "OriginAirportCode": null,
    //   "OriginCity": null,
    //   "OriginCityId": 0,
    //   "OriginCityCode": null,
    //   "OriginCountry": null,
    //   "OriginCountryId": 0,
    //   "OriginCountryCode": null,
    //   "OriginContinent": null,
    //   "OriginContinentId": 0,
    //   "OriginContinentCode": null,
    //   "DestinationAirport": "Europe",
    //   "DestinationAirportId": 0,
    //   "DestinationAirportCode": null,
    //   "DestinationCity": null,
    //   "DestinationCityId": 0,
    //   "DestinationCityCode": null,
    //   "DestinationCountry": null,
    //   "DestinationCountryId": 0,
    //   "DestinationCountryCode": null,
    //   "DestinationContinent": null,
    //   "DestinationContinentId": 0,
    //   "DestinationContinentCode": null,
    //   "SectorLength": 1794.25,
    //   "Frequency": 0,
    //   "SixMonthsFare": null,
    //   "ThreeMonthsFare": 50.5025601595951,
    //   "OneMonthFare": 38.0780973914465,
    //   "OneWeekFare": 59.5903701521354,
    //   "ForecastFare": null,
    //   "SixMonthDyf": null,
    //   "ThreeMonthDyf": null,
    //   "OneMonthDyf": null,
    //   "PublishedAirlineResult": null,
    //   "TotalCount": null,
    //   "WeightedAverage": 50.0766800486058,
    //   "FarePerDistanceUnit": 0.02790953325824484,
    //   "SectorLengthNM": 968.81749378275,
    //   "GovernmentTaxes": 0,
    //   "WeightedAverageGovernmentTaxes": 0,
    //   "CabinTypeId": 1,
    //   "CabinTypeName": "Economy"
    // },
    // {
    //   "Date": "2021-11-01T00:00:00",
    //   "Carrier": "Norwegian Air Shuttle",
    //   "CarrierId": 395,
    //   "CarrierCode": null,
    //   "OriginAirport": "Manchester International ",
    //   "OriginAirportId": 1975,
    //   "OriginAirportCode": null,
    //   "OriginCity": null,
    //   "OriginCityId": 0,
    //   "OriginCityCode": null,
    //   "OriginCountry": null,
    //   "OriginCountryId": 0,
    //   "OriginCountryCode": null,
    //   "OriginContinent": null,
    //   "OriginContinentId": 0,
    //   "OriginContinentCode": null,
    //   "DestinationAirport": "Europe",
    //   "DestinationAirportId": 0,
    //   "DestinationAirportCode": null,
    //   "DestinationCity": null,
    //   "DestinationCityId": 0,
    //   "DestinationCityCode": null,
    //   "DestinationCountry": null,
    //   "DestinationCountryId": 0,
    //   "DestinationCountryCode": null,
    //   "DestinationContinent": null,
    //   "DestinationContinentId": 0,
    //   "DestinationContinentCode": null,
    //   "SectorLength": 1169.45,
    //   "Frequency": 0,
    //   "SixMonthsFare": 65.48046234821226,
    //   "ThreeMonthsFare": 67.3040453343117,
    //   "OneMonthFare": 77.5245999294703,
    //   "OneWeekFare": 84.00256976955706,
    //   "ForecastFare": null,
    //   "SixMonthDyf": null,
    //   "ThreeMonthDyf": null,
    //   "OneMonthDyf": null,
    //   "PublishedAirlineResult": null,
    //   "TotalCount": null,
    //   "WeightedAverage": 79.74152938999785,
    //   "FarePerDistanceUnit": 0.06818720714010676,
    //   "SectorLengthNM": 631.45248326835,
    //   "GovernmentTaxes": 0,
    //   "WeightedAverageGovernmentTaxes": 0,
    //   "CabinTypeId": 1,
    //   "CabinTypeName": "Economy"
    // },
    // {
    //   "Date": "2021-11-01T00:00:00",
    //   "Carrier": "Aer Lingus",
    //   "CarrierId": 416,
    //   "CarrierCode": null,
    //   "OriginAirport": "Manchester International ",
    //   "OriginAirportId": 1975,
    //   "OriginAirportCode": null,
    //   "OriginCity": null,
    //   "OriginCityId": 0,
    //   "OriginCityCode": null,
    //   "OriginCountry": null,
    //   "OriginCountryId": 0,
    //   "OriginCountryCode": null,
    //   "OriginContinent": null,
    //   "OriginContinentId": 0,
    //   "OriginContinentCode": null,
    //   "DestinationAirport": "Europe",
    //   "DestinationAirportId": 0,
    //   "DestinationAirportCode": null,
    //   "DestinationCity": null,
    //   "DestinationCityId": 0,
    //   "DestinationCityCode": null,
    //   "DestinationCountry": null,
    //   "DestinationCountryId": 0,
    //   "DestinationCountryCode": null,
    //   "DestinationContinent": null,
    //   "DestinationContinentId": 0,
    //   "DestinationContinentCode": null,
    //   "SectorLength": 283.815,
    //   "Frequency": 0,
    //   "SixMonthsFare": 56.33451944953305,
    //   "ThreeMonthsFare": 60.4217918868872,
    //   "OneMonthFare": 43.2466864899739,
    //   "OneWeekFare": 69.1070981871807,
    //   "ForecastFare": null,
    //   "SixMonthDyf": null,
    //   "ThreeMonthDyf": null,
    //   "OneMonthDyf": null,
    //   "PublishedAirlineResult": null,
    //   "TotalCount": null,
    //   "WeightedAverage": 57.89440287826865,
    //   "FarePerDistanceUnit": 0.20398640973263799,
    //   "SectorLengthNM": 153.247840043445,
    //   "GovernmentTaxes": 0,
    //   "WeightedAverageGovernmentTaxes": 0,
    //   "CabinTypeId": 1,
    //   "CabinTypeName": "Economy"
    // },
    // {
    //   "Date": "2021-11-01T00:00:00",
    //   "Carrier": "Eurowings",
    //   "CarrierId": 432,
    //   "CarrierCode": null,
    //   "OriginAirport": "Manchester International ",
    //   "OriginAirportId": 1975,
    //   "OriginAirportCode": null,
    //   "OriginCity": null,
    //   "OriginCityId": 0,
    //   "OriginCityCode": null,
    //   "OriginCountry": null,
    //   "OriginCountryId": 0,
    //   "OriginCountryCode": null,
    //   "OriginContinent": null,
    //   "OriginContinentId": 0,
    //   "OriginContinentCode": null,
    //   "DestinationAirport": "Europe",
    //   "DestinationAirportId": 0,
    //   "DestinationAirportCode": null,
    //   "DestinationCity": null,
    //   "DestinationCityId": 0,
    //   "DestinationCityCode": null,
    //   "DestinationCountry": null,
    //   "DestinationCountryId": 0,
    //   "DestinationCountryCode": null,
    //   "DestinationContinent": null,
    //   "DestinationContinentId": 0,
    //   "DestinationContinentCode": null,
    //   "SectorLength": 690.2,
    //   "Frequency": 0,
    //   "SixMonthsFare": 55.73025705886995,
    //   "ThreeMonthsFare": 54.70826322693975,
    //   "OneMonthFare": 55.1471510619113,
    //   "OneWeekFare": 126.2859417567785,
    //   "ForecastFare": null,
    //   "SixMonthDyf": null,
    //   "ThreeMonthDyf": null,
    //   "OneMonthDyf": null,
    //   "PublishedAirlineResult": null,
    //   "TotalCount": null,
    //   "WeightedAverage": 90.6726576258477,
    //   "FarePerDistanceUnit": 0.1313715700171656,
    //   "SectorLengthNM": 372.6781854306,
    //   "GovernmentTaxes": 0,
    //   "WeightedAverageGovernmentTaxes": 0,
    //   "CabinTypeId": 1,
    //   "CabinTypeName": "Economy"
    // },
    // {
    //   "Date": "2021-11-01T00:00:00",
    //   "Carrier": "Ryanair",
    //   "CarrierId": 464,
    //   "CarrierCode": null,
    //   "OriginAirport": "Manchester International ",
    //   "OriginAirportId": 1975,
    //   "OriginAirportCode": null,
    //   "OriginCity": null,
    //   "OriginCityId": 0,
    //   "OriginCityCode": null,
    //   "OriginCountry": null,
    //   "OriginCountryId": 0,
    //   "OriginCountryCode": null,
    //   "OriginContinent": null,
    //   "OriginContinentId": 0,
    //   "OriginContinentCode": null,
    //   "DestinationAirport": "Europe",
    //   "DestinationAirportId": 0,
    //   "DestinationAirportCode": null,
    //   "DestinationCity": null,
    //   "DestinationCityId": 0,
    //   "DestinationCityCode": null,
    //   "DestinationCountry": null,
    //   "DestinationCountryId": 0,
    //   "DestinationCountryCode": null,
    //   "DestinationContinent": null,
    //   "DestinationContinentId": 0,
    //   "DestinationContinentCode": null,
    //   "SectorLength": 1432.929913,
    //   "Frequency": 0,
    //   "SixMonthsFare": 43.3873878627368,
    //   "ThreeMonthsFare": 41.23381586980185,
    //   "OneMonthFare": 27.49937739715565,
    //   "OneWeekFare": 18.72625450825635,
    //   "ForecastFare": null,
    //   "SixMonthDyf": null,
    //   "ThreeMonthDyf": null,
    //   "OneMonthDyf": null,
    //   "PublishedAirlineResult": null,
    //   "TotalCount": null,
    //   "WeightedAverage": 24.4862597999706,
    //   "FarePerDistanceUnit": 0.017088246660093696,
    //   "SectorLengthNM": 773.7202547465481,
    //   "GovernmentTaxes": 0,
    //   "WeightedAverageGovernmentTaxes": 0,
    //   "CabinTypeId": 1,
    //   "CabinTypeName": "Economy"
    // },
    // {
    //   "Date": "2021-11-01T00:00:00",
    //   "Carrier": "Aurigny Air Services",
    //   "CarrierId": 504,
    //   "CarrierCode": null,
    //   "OriginAirport": "Manchester International ",
    //   "OriginAirportId": 1975,
    //   "OriginAirportCode": null,
    //   "OriginCity": null,
    //   "OriginCityId": 0,
    //   "OriginCityCode": null,
    //   "OriginCountry": null,
    //   "OriginCountryId": 0,
    //   "OriginCountryCode": null,
    //   "OriginContinent": null,
    //   "OriginContinentId": 0,
    //   "OriginContinentCode": null,
    //   "DestinationAirport": "Europe",
    //   "DestinationAirportId": 0,
    //   "DestinationAirportCode": null,
    //   "DestinationCity": null,
    //   "DestinationCityId": 0,
    //   "DestinationCityCode": null,
    //   "DestinationCountry": null,
    //   "DestinationCountryId": 0,
    //   "DestinationCountryCode": null,
    //   "DestinationContinent": null,
    //   "DestinationContinentId": 0,
    //   "DestinationContinentCode": null,
    //   "SectorLength": 458.42,
    //   "Frequency": 0,
    //   "SixMonthsFare": null,
    //   "ThreeMonthsFare": 61.71634653287,
    //   "OneMonthFare": 70.98760568436545,
    //   "OneWeekFare": 84.7830814515042,
    //   "ForecastFare": null,
    //   "SixMonthDyf": null,
    //   "ThreeMonthDyf": null,
    //   "OneMonthDyf": null,
    //   "PublishedAirlineResult": null,
    //   "TotalCount": null,
    //   "WeightedAverage": 76.9582176527853,
    //   "FarePerDistanceUnit": 0.16787709448275664,
    //   "SectorLengthNM": 247.52699763126,
    //   "GovernmentTaxes": 0,
    //   "WeightedAverageGovernmentTaxes": 0,
    //   "CabinTypeId": 1,
    //   "CabinTypeName": "Economy"
    // },
    // {
    //   "Date": "2021-11-01T00:00:00",
    //   "Carrier": "Iberia",
    //   "CarrierId": 564,
    //   "CarrierCode": null,
    //   "OriginAirport": "Manchester International ",
    //   "OriginAirportId": 1975,
    //   "OriginAirportCode": null,
    //   "OriginCity": null,
    //   "OriginCityId": 0,
    //   "OriginCityCode": null,
    //   "OriginCountry": null,
    //   "OriginCountryId": 0,
    //   "OriginCountryCode": null,
    //   "OriginContinent": null,
    //   "OriginContinentId": 0,
    //   "OriginContinentCode": null,
    //   "DestinationAirport": "Europe",
    //   "DestinationAirportId": 0,
    //   "DestinationAirportCode": null,
    //   "DestinationCity": null,
    //   "DestinationCityId": 0,
    //   "DestinationCityCode": null,
    //   "DestinationCountry": null,
    //   "DestinationCountryId": 0,
    //   "DestinationCountryCode": null,
    //   "DestinationContinent": null,
    //   "DestinationContinentId": 0,
    //   "DestinationContinentCode": null,
    //   "SectorLength": 1504.6,
    //   "Frequency": 0,
    //   "SixMonthsFare": 36.251427279852,
    //   "ThreeMonthsFare": 39.4380634489541,
    //   "OneMonthFare": 48.737253270049,
    //   "OneWeekFare": 73.74987012137144,
    //   "ForecastFare": null,
    //   "SixMonthDyf": null,
    //   "ThreeMonthDyf": null,
    //   "OneMonthDyf": null,
    //   "PublishedAirlineResult": null,
    //   "TotalCount": null,
    //   "WeightedAverage": 60.3136427136007,
    //   "FarePerDistanceUnit": 0.04008616423873501,
    //   "SectorLengthNM": 812.4190057938,
    //   "GovernmentTaxes": 0,
    //   "WeightedAverageGovernmentTaxes": 0,
    //   "CabinTypeId": 1,
    //   "CabinTypeName": "Economy"
    // },
    // {
    //   "Date": "2021-11-01T00:00:00",
    //   "Carrier": "KLM",
    //   "CarrierId": 652,
    //   "CarrierCode": null,
    //   "OriginAirport": "Manchester International ",
    //   "OriginAirportId": 1975,
    //   "OriginAirportCode": null,
    //   "OriginCity": null,
    //   "OriginCityId": 0,
    //   "OriginCityCode": null,
    //   "OriginCountry": null,
    //   "OriginCountryId": 0,
    //   "OriginCountryCode": null,
    //   "OriginContinent": null,
    //   "OriginContinentId": 0,
    //   "OriginContinentCode": null,
    //   "DestinationAirport": "Europe",
    //   "DestinationAirportId": 0,
    //   "DestinationAirportCode": null,
    //   "DestinationCity": null,
    //   "DestinationCityId": 0,
    //   "DestinationCityCode": null,
    //   "DestinationCountry": null,
    //   "DestinationCountryId": 0,
    //   "DestinationCountryCode": null,
    //   "DestinationContinent": null,
    //   "DestinationContinentId": 0,
    //   "DestinationContinentCode": null,
    //   "SectorLength": 512.68,
    //   "Frequency": 0,
    //   "SixMonthsFare": 48.89345972451045,
    //   "ThreeMonthsFare": 47.3504155685528,
    //   "OneMonthFare": 52.9271996786093,
    //   "OneWeekFare": 66.07625255266325,
    //   "ForecastFare": null,
    //   "SixMonthDyf": null,
    //   "ThreeMonthDyf": null,
    //   "OneMonthDyf": null,
    //   "PublishedAirlineResult": null,
    //   "TotalCount": null,
    //   "WeightedAverage": 58.94404770463065,
    //   "FarePerDistanceUnit": 0.11497239546038591,
    //   "SectorLengthNM": 276.82505376204,
    //   "GovernmentTaxes": 0,
    //   "WeightedAverageGovernmentTaxes": 0,
    //   "CabinTypeId": 1,
    //   "CabinTypeName": "Economy"
    // },
    // {
    //   "Date": "2021-11-01T00:00:00",
    //   "Carrier": "Lufthansa",
    //   "CarrierId": 684,
    //   "CarrierCode": null,
    //   "OriginAirport": "Manchester International ",
    //   "OriginAirportId": 1975,
    //   "OriginAirportCode": null,
    //   "OriginCity": null,
    //   "OriginCityId": 0,
    //   "OriginCityCode": null,
    //   "OriginCountry": null,
    //   "OriginCountryId": 0,
    //   "OriginCountryCode": null,
    //   "OriginContinent": null,
    //   "OriginContinentId": 0,
    //   "OriginContinentCode": null,
    //   "DestinationAirport": "Europe",
    //   "DestinationAirportId": 0,
    //   "DestinationAirportCode": null,
    //   "DestinationCity": null,
    //   "DestinationCityId": 0,
    //   "DestinationCityCode": null,
    //   "DestinationCountry": null,
    //   "DestinationCountryId": 0,
    //   "DestinationCountryCode": null,
    //   "DestinationContinent": null,
    //   "DestinationContinentId": 0,
    //   "DestinationContinentCode": null,
    //   "SectorLength": 1002.712325,
    //   "Frequency": 0,
    //   "SixMonthsFare": 57.36353881967945,
    //   "ThreeMonthsFare": 59.6157765023476,
    //   "OneMonthFare": 70.3565241738984,
    //   "OneWeekFare": 98.62401059268565,
    //   "ForecastFare": null,
    //   "SixMonthDyf": null,
    //   "ThreeMonthDyf": null,
    //   "OneMonthDyf": null,
    //   "PublishedAirlineResult": null,
    //   "TotalCount": null,
    //   "WeightedAverage": 83.41619261613695,
    //   "FarePerDistanceUnit": 0.08319055280001365,
    //   "SectorLengthNM": 541.421341335697,
    //   "GovernmentTaxes": 0,
    //   "WeightedAverageGovernmentTaxes": 0,
    //   "CabinTypeId": 1,
    //   "CabinTypeName": "Economy"
    // },
    // {
    //   "Date": "2021-11-01T00:00:00",
    //   "Carrier": "Jet2",
    //   "CarrierId": 698,
    //   "CarrierCode": null,
    //   "OriginAirport": "Manchester International ",
    //   "OriginAirportId": 1975,
    //   "OriginAirportCode": null,
    //   "OriginCity": null,
    //   "OriginCityId": 0,
    //   "OriginCityCode": null,
    //   "OriginCountry": null,
    //   "OriginCountryId": 0,
    //   "OriginCountryCode": null,
    //   "OriginContinent": null,
    //   "OriginContinentId": 0,
    //   "OriginContinentCode": null,
    //   "DestinationAirport": "Europe",
    //   "DestinationAirportId": 0,
    //   "DestinationAirportCode": null,
    //   "DestinationCity": null,
    //   "DestinationCityId": 0,
    //   "DestinationCityCode": null,
    //   "DestinationCountry": null,
    //   "DestinationCountryId": 0,
    //   "DestinationCountryCode": null,
    //   "DestinationContinent": null,
    //   "DestinationContinentId": 0,
    //   "DestinationContinentCode": null,
    //   "SectorLength": 2630.397346,
    //   "Frequency": 0,
    //   "SixMonthsFare": 102.8904675705171,
    //   "ThreeMonthsFare": 83.6915442474655,
    //   "OneMonthFare": 79.60804343459814,
    //   "OneWeekFare": 73.47279146677215,
    //   "ForecastFare": null,
    //   "SixMonthDyf": null,
    //   "ThreeMonthDyf": null,
    //   "OneMonthDyf": null,
    //   "PublishedAirlineResult": null,
    //   "TotalCount": null,
    //   "WeightedAverage": 76.94876753197185,
    //   "FarePerDistanceUnit": 0.02925366680778724,
    //   "SectorLengthNM": 1420.3009415658448,
    //   "GovernmentTaxes": 0,
    //   "WeightedAverageGovernmentTaxes": 0,
    //   "CabinTypeId": 1,
    //   "CabinTypeName": "Economy"
    // },
    // {
    //   "Date": "2021-11-01T00:00:00",
    //   "Carrier": "SWISS",
    //   "CarrierId": 703,
    //   "CarrierCode": null,
    //   "OriginAirport": "Manchester International ",
    //   "OriginAirportId": 1975,
    //   "OriginAirportCode": null,
    //   "OriginCity": null,
    //   "OriginCityId": 0,
    //   "OriginCityCode": null,
    //   "OriginCountry": null,
    //   "OriginCountryId": 0,
    //   "OriginCountryCode": null,
    //   "OriginContinent": null,
    //   "OriginContinentId": 0,
    //   "OriginContinentCode": null,
    //   "DestinationAirport": "Europe",
    //   "DestinationAirportId": 0,
    //   "DestinationAirportCode": null,
    //   "DestinationCity": null,
    //   "DestinationCityId": 0,
    //   "DestinationCityCode": null,
    //   "DestinationCountry": null,
    //   "DestinationCountryId": 0,
    //   "DestinationCountryCode": null,
    //   "DestinationContinent": null,
    //   "DestinationContinentId": 0,
    //   "DestinationContinentCode": null,
    //   "SectorLength": 1059.04,
    //   "Frequency": 0,
    //   "SixMonthsFare": 60.7499510613069,
    //   "ThreeMonthsFare": 73.6595195435851,
    //   "OneMonthFare": 91.37387678445894,
    //   "OneWeekFare": 137.272492062447,
    //   "ForecastFare": null,
    //   "SixMonthDyf": null,
    //   "ThreeMonthDyf": null,
    //   "OneMonthDyf": null,
    //   "PublishedAirlineResult": null,
    //   "TotalCount": null,
    //   "WeightedAverage": 112.5517486993655,
    //   "FarePerDistanceUnit": 0.10627714599955196,
    //   "SectorLengthNM": 571.83585264912,
    //   "GovernmentTaxes": 0,
    //   "WeightedAverageGovernmentTaxes": 0,
    //   "CabinTypeId": 1,
    //   "CabinTypeName": "Economy"
    // },
    // {
    //   "Date": "2021-11-01T00:00:00",
    //   "Carrier": "Austrian",
    //   "CarrierId": 817,
    //   "CarrierCode": null,
    //   "OriginAirport": "Manchester International ",
    //   "OriginAirportId": 1975,
    //   "OriginAirportCode": null,
    //   "OriginCity": null,
    //   "OriginCityId": 0,
    //   "OriginCityCode": null,
    //   "OriginCountry": null,
    //   "OriginCountryId": 0,
    //   "OriginCountryCode": null,
    //   "OriginContinent": null,
    //   "OriginContinentId": 0,
    //   "OriginContinentCode": null,
    //   "DestinationAirport": "Europe",
    //   "DestinationAirportId": 0,
    //   "DestinationAirportCode": null,
    //   "DestinationCity": null,
    //   "DestinationCityId": 0,
    //   "DestinationCityCode": null,
    //   "DestinationCountry": null,
    //   "DestinationCountryId": 0,
    //   "DestinationCountryCode": null,
    //   "DestinationContinent": null,
    //   "DestinationContinentId": 0,
    //   "DestinationContinentCode": null,
    //   "SectorLength": 1519.97,
    //   "Frequency": 0,
    //   "SixMonthsFare": null,
    //   "ThreeMonthsFare": 70.5500291418668,
    //   "OneMonthFare": 68.64055784782104,
    //   "OneWeekFare": 113.13177476918095,
    //   "ForecastFare": null,
    //   "SixMonthDyf": null,
    //   "ThreeMonthDyf": null,
    //   "OneMonthDyf": null,
    //   "PublishedAirlineResult": null,
    //   "TotalCount": null,
    //   "WeightedAverage": 91.0771134379057,
    //   "FarePerDistanceUnit": 0.059920336215784326,
    //   "SectorLengthNM": 820.71814185591,
    //   "GovernmentTaxes": 0,
    //   "WeightedAverageGovernmentTaxes": 0,
    //   "CabinTypeId": 1,
    //   "CabinTypeName": "Economy"
    // },
    // {
    //   "Date": "2021-11-01T00:00:00",
    //   "Carrier": "Blue Islands",
    //   "CarrierId": 971,
    //   "CarrierCode": null,
    //   "OriginAirport": "Manchester International ",
    //   "OriginAirportId": 1975,
    //   "OriginAirportCode": null,
    //   "OriginCity": null,
    //   "OriginCityId": 0,
    //   "OriginCityCode": null,
    //   "OriginCountry": null,
    //   "OriginCountryId": 0,
    //   "OriginCountryCode": null,
    //   "OriginContinent": null,
    //   "OriginContinentId": 0,
    //   "OriginContinentCode": null,
    //   "DestinationAirport": "Europe",
    //   "DestinationAirportId": 0,
    //   "DestinationAirportCode": null,
    //   "DestinationCity": null,
    //   "DestinationCityId": 0,
    //   "DestinationCityCode": null,
    //   "DestinationCountry": null,
    //   "DestinationCountryId": 0,
    //   "DestinationCountryCode": null,
    //   "DestinationContinent": null,
    //   "DestinationContinentId": 0,
    //   "DestinationContinentCode": null,
    //   "SectorLength": 316.8,
    //   "Frequency": 0,
    //   "SixMonthsFare": null,
    //   "ThreeMonthsFare": 44.00632712555255,
    //   "OneMonthFare": 58.4940243306299,
    //   "OneWeekFare": 87.9942083169061,
    //   "ForecastFare": null,
    //   "SixMonthDyf": null,
    //   "ThreeMonthDyf": null,
    //   "OneMonthDyf": null,
    //   "PublishedAirlineResult": null,
    //   "TotalCount": null,
    //   "WeightedAverage": 71.79534660326026,
    //   "FarePerDistanceUnit": 0.22662672538907908,
    //   "SectorLengthNM": 171.0583151904,
    //   "GovernmentTaxes": 0,
    //   "WeightedAverageGovernmentTaxes": 0,
    //   "CabinTypeId": 1,
    //   "CabinTypeName": "Economy"
    // },
    // {
    //   "Date": "2021-11-01T00:00:00",
    //   "Carrier": "SAS",
    //   "CarrierId": 974,
    //   "CarrierCode": null,
    //   "OriginAirport": "Manchester International ",
    //   "OriginAirportId": 1975,
    //   "OriginAirportCode": null,
    //   "OriginCity": null,
    //   "OriginCityId": 0,
    //   "OriginCityCode": null,
    //   "OriginCountry": null,
    //   "OriginCountryId": 0,
    //   "OriginCountryCode": null,
    //   "OriginContinent": null,
    //   "OriginContinentId": 0,
    //   "OriginContinentCode": null,
    //   "DestinationAirport": "Europe",
    //   "DestinationAirportId": 0,
    //   "DestinationAirportCode": null,
    //   "DestinationCity": null,
    //   "DestinationCityId": 0,
    //   "DestinationCityCode": null,
    //   "DestinationCountry": null,
    //   "DestinationCountryId": 0,
    //   "DestinationCountryCode": null,
    //   "DestinationContinent": null,
    //   "DestinationContinentId": 0,
    //   "DestinationContinentCode": null,
    //   "SectorLength": 1238.206352,
    //   "Frequency": 0,
    //   "SixMonthsFare": 55.3124527773258,
    //   "ThreeMonthsFare": 78.90929680278245,
    //   "OneMonthFare": 88.7232927125237,
    //   "OneWeekFare": 152.523510670273,
    //   "ForecastFare": null,
    //   "SixMonthDyf": null,
    //   "ThreeMonthDyf": null,
    //   "OneMonthDyf": null,
    //   "PublishedAirlineResult": null,
    //   "TotalCount": null,
    //   "WeightedAverage": 119.642002100424,
    //   "FarePerDistanceUnit": 0.09662525305832384,
    //   "SectorLengthNM": 668.5779432802127,
    //   "GovernmentTaxes": 0,
    //   "WeightedAverageGovernmentTaxes": 0,
    //   "CabinTypeId": 1,
    //   "CabinTypeName": "Economy"
    // },
    // {
    //   "Date": "2021-11-01T00:00:00",
    //   "Carrier": "Brussels Airlines",
    //   "CarrierId": 977,
    //   "CarrierCode": null,
    //   "OriginAirport": "Manchester International ",
    //   "OriginAirportId": 1975,
    //   "OriginAirportCode": null,
    //   "OriginCity": null,
    //   "OriginCityId": 0,
    //   "OriginCityCode": null,
    //   "OriginCountry": null,
    //   "OriginCountryId": 0,
    //   "OriginCountryCode": null,
    //   "OriginContinent": null,
    //   "OriginContinentId": 0,
    //   "OriginContinentCode": null,
    //   "DestinationAirport": "Europe",
    //   "DestinationAirportId": 0,
    //   "DestinationAirportCode": null,
    //   "DestinationCity": null,
    //   "DestinationCityId": 0,
    //   "DestinationCityCode": null,
    //   "DestinationCountry": null,
    //   "DestinationCountryId": 0,
    //   "DestinationCountryCode": null,
    //   "DestinationContinent": null,
    //   "DestinationContinentId": 0,
    //   "DestinationContinentCode": null,
    //   "SectorLength": 563.86,
    //   "Frequency": 0,
    //   "SixMonthsFare": 46.93392311478875,
    //   "ThreeMonthsFare": 45.84045726648385,
    //   "OneMonthFare": 49.47441269885535,
    //   "OneWeekFare": 94.88731420366734,
    //   "ForecastFare": null,
    //   "SixMonthDyf": null,
    //   "ThreeMonthDyf": null,
    //   "OneMonthDyf": null,
    //   "PublishedAirlineResult": null,
    //   "TotalCount": null,
    //   "WeightedAverage": 71.81746790802416,
    //   "FarePerDistanceUnit": 0.12736755206615855,
    //   "SectorLengthNM": 304.46004293958,
    //   "GovernmentTaxes": 0,
    //   "WeightedAverageGovernmentTaxes": 0,
    //   "CabinTypeId": 1,
    //   "CabinTypeName": "Economy"
    // },
    // {
    //   "Date": "2021-11-01T00:00:00",
    //   "Carrier": "Eastern Airways",
    //   "CarrierId": 995,
    //   "CarrierCode": null,
    //   "OriginAirport": "Manchester International ",
    //   "OriginAirportId": 1975,
    //   "OriginAirportCode": null,
    //   "OriginCity": null,
    //   "OriginCityId": 0,
    //   "OriginCityCode": null,
    //   "OriginCountry": null,
    //   "OriginCountryId": 0,
    //   "OriginCountryCode": null,
    //   "OriginContinent": null,
    //   "OriginContinentId": 0,
    //   "OriginContinentCode": null,
    //   "DestinationAirport": "Europe",
    //   "DestinationAirportId": 0,
    //   "DestinationAirportCode": null,
    //   "DestinationCity": null,
    //   "DestinationCityId": 0,
    //   "DestinationCityCode": null,
    //   "DestinationCountry": null,
    //   "DestinationCountryId": 0,
    //   "DestinationCountryCode": null,
    //   "DestinationContinent": null,
    //   "DestinationContinentId": 0,
    //   "DestinationContinentCode": null,
    //   "SectorLength": 288.44,
    //   "Frequency": 0,
    //   "SixMonthsFare": null,
    //   "ThreeMonthsFare": 77.9931851789017,
    //   "OneMonthFare": 79.4691756640802,
    //   "OneWeekFare": 85.48723872978255,
    //   "ForecastFare": null,
    //   "SixMonthDyf": null,
    //   "ThreeMonthDyf": null,
    //   "OneMonthDyf": null,
    //   "PublishedAirlineResult": null,
    //   "TotalCount": null,
    //   "WeightedAverage": 82.3306081484135,
    //   "FarePerDistanceUnit": 0.28543408732635384,
    //   "SectorLengthNM": 155.74514025732,
    //   "GovernmentTaxes": 0,
    //   "WeightedAverageGovernmentTaxes": 0,
    //   "CabinTypeId": 1,
    //   "CabinTypeName": "Economy"
    // },
    // {
    //   "Date": "2021-11-01T00:00:00",
    //   "Carrier": "TAP Air Portugal",
    //   "CarrierId": 1024,
    //   "CarrierCode": null,
    //   "OriginAirport": "Manchester International ",
    //   "OriginAirportId": 1975,
    //   "OriginAirportCode": null,
    //   "OriginCity": null,
    //   "OriginCityId": 0,
    //   "OriginCityCode": null,
    //   "OriginCountry": null,
    //   "OriginCountryId": 0,
    //   "OriginCountryCode": null,
    //   "OriginContinent": null,
    //   "OriginContinentId": 0,
    //   "OriginContinentCode": null,
    //   "DestinationAirport": "Europe",
    //   "DestinationAirportId": 0,
    //   "DestinationAirportCode": null,
    //   "DestinationCity": null,
    //   "DestinationCityId": 0,
    //   "DestinationCityCode": null,
    //   "DestinationCountry": null,
    //   "DestinationCountryId": 0,
    //   "DestinationCountryCode": null,
    //   "DestinationContinent": null,
    //   "DestinationContinentId": 0,
    //   "DestinationContinentCode": null,
    //   "SectorLength": 1788.45,
    //   "Frequency": 0,
    //   "SixMonthsFare": 56.83087784186345,
    //   "ThreeMonthsFare": 60.80354688133685,
    //   "OneMonthFare": 72.449214896654,
    //   "OneWeekFare": 84.4352447236799,
    //   "ForecastFare": null,
    //   "SixMonthDyf": null,
    //   "ThreeMonthDyf": null,
    //   "OneMonthDyf": null,
    //   "PublishedAirlineResult": null,
    //   "TotalCount": null,
    //   "WeightedAverage": 77.2776630086352,
    //   "FarePerDistanceUnit": 0.0432092946454389,
    //   "SectorLengthNM": 965.68574432535,
    //   "GovernmentTaxes": 0,
    //   "WeightedAverageGovernmentTaxes": 0,
    //   "CabinTypeId": 1,
    //   "CabinTypeName": "Economy"
    // },
    // {
    //   "Date": "2021-11-01T00:00:00",
    //   "Carrier": "easyJet",
    //   "CarrierId": 1038,
    //   "CarrierCode": null,
    //   "OriginAirport": "Manchester International ",
    //   "OriginAirportId": 1975,
    //   "OriginAirportCode": null,
    //   "OriginCity": null,
    //   "OriginCityId": 0,
    //   "OriginCityCode": null,
    //   "OriginCountry": null,
    //   "OriginCountryId": 0,
    //   "OriginCountryCode": null,
    //   "OriginContinent": null,
    //   "OriginContinentId": 0,
    //   "OriginContinentCode": null,
    //   "DestinationAirport": "Europe",
    //   "DestinationAirportId": 0,
    //   "DestinationAirportCode": null,
    //   "DestinationCity": null,
    //   "DestinationCityId": 0,
    //   "DestinationCityCode": null,
    //   "DestinationCountry": null,
    //   "DestinationCountryId": 0,
    //   "DestinationCountryCode": null,
    //   "DestinationContinent": null,
    //   "DestinationContinentId": 0,
    //   "DestinationContinentCode": null,
    //   "SectorLength": 1304.216909,
    //   "Frequency": 0,
    //   "SixMonthsFare": 47.88487492329625,
    //   "ThreeMonthsFare": 38.46413787652185,
    //   "OneMonthFare": 51.08568061079665,
    //   "OneWeekFare": 52.339106721921,
    //   "ForecastFare": null,
    //   "SixMonthDyf": null,
    //   "ThreeMonthDyf": null,
    //   "OneMonthDyf": null,
    //   "PublishedAirlineResult": null,
    //   "TotalCount": null,
    //   "WeightedAverage": 50.4502393929313,
    //   "FarePerDistanceUnit": 0.038682399411317014,
    //   "SectorLengthNM": 704.220792602182,
    //   "GovernmentTaxes": 0,
    //   "WeightedAverageGovernmentTaxes": 0,
    //   "CabinTypeId": 1,
    //   "CabinTypeName": "Economy"
    // },
    // {
    //   "Date": "2021-11-01T00:00:00",
    //   "Carrier": "Vueling",
    //   "CarrierId": 1118,
    //   "CarrierCode": null,
    //   "OriginAirport": "Manchester International ",
    //   "OriginAirportId": 1975,
    //   "OriginAirportCode": null,
    //   "OriginCity": null,
    //   "OriginCityId": 0,
    //   "OriginCityCode": null,
    //   "OriginCountry": null,
    //   "OriginCountryId": 0,
    //   "OriginCountryCode": null,
    //   "OriginContinent": null,
    //   "OriginContinentId": 0,
    //   "OriginContinentCode": null,
    //   "DestinationAirport": "Europe",
    //   "DestinationAirportId": 0,
    //   "DestinationAirportCode": null,
    //   "DestinationCity": null,
    //   "DestinationCityId": 0,
    //   "DestinationCityCode": null,
    //   "DestinationCountry": null,
    //   "DestinationCountryId": 0,
    //   "DestinationCountryCode": null,
    //   "DestinationContinent": null,
    //   "DestinationContinentId": 0,
    //   "DestinationContinentCode": null,
    //   "SectorLength": 1448.54,
    //   "Frequency": 0,
    //   "SixMonthsFare": null,
    //   "ThreeMonthsFare": 32.79254075227765,
    //   "OneMonthFare": 39.8532111883997,
    //   "OneWeekFare": 35.74658665091435,
    //   "ForecastFare": null,
    //   "SixMonthDyf": null,
    //   "ThreeMonthDyf": null,
    //   "OneMonthDyf": null,
    //   "PublishedAirlineResult": null,
    //   "TotalCount": null,
    //   "WeightedAverage": 37.09383187604485,
    //   "FarePerDistanceUnit": 0.02560773736040762,
    //   "SectorLengthNM": 782.14902741762,
    //   "GovernmentTaxes": 0,
    //   "WeightedAverageGovernmentTaxes": 0,
    //   "CabinTypeId": 1,
    //   "CabinTypeName": "Economy"
    // }
]
